import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.feature_extraction.text import TfidfVectorizer



training_queries = {
    "query": [

        # DISREPAIR AND CONDITIONS

        "My boiler makes banging noises and isn’t keeping us warm",
        "The communal lighting in the stairwell is broken",
        "There’s a constant drip from the kitchen ceiling",
        "The patio door frame is rotten and lets in pests",
        "Tiles are cracking all over the kitchen floor",
        "My radiator is cold at the bottom but hot at the top",
        "The extractor fan in the kitchen is completely seized",
        "The concrete steps outside are crumbling away",
        "I reported a fault 10 days ago and still no fix",
        "The communal heating timer isn’t programmable",
        "My garage door opener has stopped working",
        "The window seal is broken and rain is leaking in",
        "The pipe under my sink rattles all night",
        "They fitted the wrong lightbulbs and left bare wiring",
        "My extractor fan smells like burning wires",
        "The guttering outside is detached and overflows",
        "The communal garden fence is falling over",
        "My burglar alarm power supply is faulty",
        "The electrical sockets spark when I plug in appliances",
        "They painted over my fire exit signage",
        "The hallway carpet is torn and a trip hazard",
        "My downstairs toilet cistern won’t refill",
        "The sprinkler system has been leaking for weeks",
        "The loft hatch is broken and can’t be closed",
        "My walls have peeling paint and damp patches",
        "The kitchen tap handle has snapped off",
        "My bedroom radiator leaks steam and water",
        "The wallpaper is bubbling and peeling in several rooms",
        "There’s a crack in the foundation by the front step",
        "The hallway floorboards creak and are coming loose",
        "The bathroom grout is mouldy and falling out",
        "The kitchen cupboard doors won’t stay closed",
        "The external light sensor doesn’t turn on at dusk",
        "My window lock is missing a key",
        "The gas fire pilot light keeps going out",
        "The fence between my garden and the next is broken",
        "The pantry cupboard has sagged off its hinges",
        "The stair nosing is worn and a tripping hazard",
        "The soffit under the roof is rotten and falling",
        "My loft insulation is missing and drafty",
        "The communal bench in the courtyard is splintered",
        "The smoke alarm wiring is loose in the ceiling",
        "The extractor ductwork is clogged with debris",
        "The touch-sensitive light switch doesn’t respond",
        "The toilet seat is cracked and unsafe",
        "The front door peephole is smashed",
        "The pathway outside has sunken paving slabs",
        "The cold water tank in the loft is corroded",
        "The basement door seal is torn and lets in pests",
        "The loft ladder mechanism is jammed",

        # TENANCY, TRANSFER, RENT AND EVICTION

        "They increased my rent without notice",
        "I want to swap flats with another tenant",
        "Can they force me to take in a lodger?",
        "They’ve backdated rent arrears I wasn’t told about",
        "I’ve paid my rent but they still claim I’m in arrears",
        "Can I get written proof of my rent payments?",
        "I want advice on ending my tenancy early",
        "They’re refusing to renew my tenancy because of my benefits",
        "Can they increase my rent mid-tenancy?",
        "I want to appeal my banding decision",
        "They threatened court over a disputed repair",
        "Can they charge me for a tenancy inspection?",
        "I need to add my partner to the tenancy",
        "They changed the rent due date without warning",
        "I’ve been told I must pay a holding deposit",
        "Can I challenge an unlawful eviction attempt?",
        "They locked me out without a court order",
        "I’m on a joint lease but my ex has gone",
        "They listed me as short-term when I’m permanent",
        "My tenancy was transferred without my permission",
        "They won’t explain new clauses in my agreement",
        "Can they refuse to transfer me to ground floor?",
        "I want to dispute an illegal fee charge",
        "They threatened eviction for minor damage",
        "I’m served notice indefinitely—what does that mean?",
        "Can they increase my rent twice in one year?",
        "What notice period must they give before eviction?",
        "I want to transfer to a smaller property—how do I apply?",
        "They’re charging me for a tenancy check I didn’t agree to",
        "Can I sublet my room to help cover rent?",
        "They served me a Section 8 notice for minor damage",
        "I need advice on renewing my tenancy under new terms",
        "They backdated my rent review by six months",
        "Can they demand rent on a week-to-week basis?",
        "They’re threatening court over alleged non-payment",
        "I want to change my tenancy from fixed to periodic",
        "They refused my request to end the tenancy early",
        "Can they refuse a mutual exchange I’ve been offered?",
        "They’re deducting costs from my deposit for wear and tear",
        "I want clarity on break clauses in my lease",
        "They increased my service charge without consultation",
        "Can I dispute an unlawful eviction attempt?",
        "They’re insisting on references for a transfer application",
        "I’ve been told I must sign a new tenancy agreement mid-term",
        "Can they repossess if I miss one rent payment?",
        "They served me with notice for anti-social behaviour allegations",
        "I want to add my partner to the tenancy agreement",
        "They’re refusing to move me despite an approved medical transfer",
        "Can they charge a fee for checking the inventory on exit?",
        "They changed my tenancy start date without my knowledge",


        # ACCESSIBILITY AND DISCRIMINATION

        "They denied my carer a parking permit",
        "I’m autistic and they ignore my communication needs",
        "My oxygen cylinder won’t fit through the hallway door",
        "They refuse to consider my unseen disability",
        "My hearing aid batteries aren’t reimbursed",
        "They moved me after I complained about discrimination",
        "The intercom doesn’t relay for my hearing loss",
        "I need tactile signage for my vision impairment",
        "They ignored my Equality Act reasonable adjustments",
        "My mental health support letters were disregarded",
        "They refused to grant me a live-in personal assistant",
        "I need grab rails in the communal bathroom",
        "They say my service animal isn’t covered by policy",
        "I was penalised for late rent due to my condition",
        "They scheduled inspections without accessible notice",
        "They refused to translate documents into Braille",
        "I can’t reach the postbox from my wheelchair",
        "They forced me to use stairs despite my MS",
        "My request for a supportive housing transfer was rejected",
        "They said I’m not disabled enough for priority",
        "They denied my adaptation grant application",
        "I need a stairlift for my elderly parent",
        "They cancelled my medical priority allocation",
        "They said pets aren’t allowed despite my ESA letter",
        "They won’t allow my carer to have a key for emergencies",
        "I need a lowered worktop in the kitchen for my wheelchair",
        "The tactile paving at the entrance is worn away",
        "They refuse to install a hearing loop in the meeting room",
        "I need automatic window openers for fresh air access",
        "They denied my request for visual alarms in the hallway",
        "The call bell in the bathroom is too high for me to reach",
        "They won’t install non-slip flooring in the wet areas",
        "My ramp request was rejected due to budget constraints",
        "They refuse to adapt the bathroom for my mobility needs",
        "I need Braille labels on all fire doors",
        "They won’t provide a BSL interpreter for meetings",
        "The communal phones aren’t accessible to screen readers",
        "They’ve blocked my disabled parking bay without warning",
        "I need lower light switches for my reach limitations",
        "They deny my request for grab rails in the hallway",
        "I’m being refused a stairlift despite medical evidence",
        "They won’t allow me to install a step-free shower",
        "I need door handles that are easy to grip",
        "They rejected my application for priority rehousing",
        "They refuse to provide written minutes in large print",
        "The audible fire alarm is too faint for my hearing aid",
        "I need a hoist fitting in my bedroom for transfers",
        "They won’t allow modifications to fit my CPAP machine",
        "They say I don’t qualify for reasonable adjustments",

        # COMPLAINTS AND OMBUDSMAN

        "My caseworker refuses to meet me in person",
        "They replied to the wrong person about my complaint",
        "I want status updates but they won’t tell me",
        "They misrepresented facts in their response to me",
        "My complaint was only handled by a junior officer",
        "They closed my file without notifying me",
        "I never got the outcome letter they promised",
        "They disputed my version of events in writing",
        "I want to submit additional evidence to my complaint",
        "They won’t provide a clear timeline for resolution",
        "They ignored my request for an independent review",
        "I was told to use the web portal but it doesn’t work",
        "They offered mediation but then withdrew it",
        "They’ve given conflicting reasons for delays",
        "I want compensation for distress caused",
        "They said my complaint was out of time when it wasn’t",
        "My complaint was escalated but no one followed up",
        "They refused to log my harassment report",
        "I asked for an apology and got none",
        "They lost my formal letter and said it was never sent",
        "I’m being transferred departments mid-complaint",
        "They won’t tell me who is investigating",
        "I need guidance on Ombudsman deadlines",
        "They only respond to complaints by phone",
        "They denied me the right to escalate",
        "They closed my complaint as ‘invalid’ without explanation",
        "I want to know why my formal complaint was downgraded",
        "They refuse to provide me with their complaints procedure",
        "I asked for a summary of all complaints against my estate",
        "They ignored my request to meet with a senior manager",
        "My complaint response deadline passed without any acknowledgment",
        "They said they’ll investigate but haven’t updated me",
        "I want to see the log of every time I’ve contacted them",
        "They keep asking me for the same information I’ve already given",
        "I requested mediation but they only offered an apology",
        "They changed the outcome after I asked for further review",
        "They refuse to explain the criteria used to assess my complaint",
        "My complaint was closed before they resolved the repairs issue",
        "They sent me a generic response that doesn’t address my points",
        "I’m being bounced between departments when I complain",
        "They promised a written outcome and sent only an email",
        "They lost my complaint form and asked me to start again",
        "I asked for compensation and they offered none",
        "They refuse to let me escalate to their board",
        "I want to know who’s responsible for responding to complaints",
        "They said I’m ‘time-barred’ from complaining when I’m not",
        "They won’t acknowledge my complaint about discrimination",
        "My follow-up questions to their response were ignored",
        "They refuse to keep minutes of our complaint meetings",
        "They haven’t provided the Ombudsman’s contact details",
            

        # ANTISOCIAL BEHAVIOUR AND NEIGHBOUR CONFLICT

        "People smoke cannabis in the stairwell every night",
        "They play football against my door",
        "My neighbour’s parties go on until dawn",
        "They spray graffiti on my front door",
        "There’s fighting in the corridor most evenings",
        "They shout racist abuse at my family",
        "Their CCTV camera shines into my bedroom",
        "They leave shopping trolleys blocking access",
        "My neighbour dumps furniture in the bin store",
        "They invited a large group and it got out of hand",
        "They’re drilling holes late at night",
        "My parking space is taken by another tenant",
        "They scatter broken glass on my path",
        "They’ve threatened me when I asked them to stop",
        "Our car tyres have been slashed twice",
        "They’re selling stolen goods from their flat",
        "They leave dirty nappies in the hallway",
        "My neighbour’s smoke fills my home",
        "They play drums at 3am every morning",
        "They keep inviting strangers into the building",
        "They threaten my children when they walk by",
        "They blocked the fire exit with junk",
        "They called me names in the communal garden",
        "They’ve been reported for harassment but no action",
        "They blast TV at full volume at 3 am every night",
        "My neighbour’s pet parrot screams all day long",
        "They’ve been dumping furniture in front of my door",
        "Someone’s vaping in the lift despite the no-smoking sign",
        "They’ve been riding a motorbike around the courtyard",
        "They play loud video games until dawn",
        "My neighbour’s friends park across my driveway",
        "They keep dumping dog waste in my garden",
        "They’ve been spray-painting graffiti on communal walls",
        "They shine a spotlight into my bedroom window",
        "They’ve been playing drums in the hallway",
        "They host loud karaoke parties every weekend",
        "They let their children run wild in the stairwell",
        "They’ve been leaving broken glass on the steps",
        "They burst into my flat without warning",
        "They leave shopping trollies blocking fire exits",
        "They’ve been shooting BB guns at passersby",
        "They call me names and shout abuse through the walls",
        "They blast car horns at odd hours for fun",
        "They’ve been stockpiling rubbish in the communal bin room",
        "They intimidate my visitors in the foyer",
        "They hang offensive banners from their balcony",
        "They’ve been spitting in the communal lift",
        "They’ve threatened to throw my belongings out",
        "They keep setting off car alarms in the car park",

        # HOMELESSNESS

        "I’ve been waiting for a decision on my homelessness application",
        "They told me to stay with friends but it’s not permanent",
        "My temporary flat is infested with bedbugs",
        "They said I’m not priority even though I’m pregnant",
        "I’ve been evicted and have nowhere safe to go",
        "They offered me a hostel 50 miles from here",
        "I’ve been refused because I missed a letter",
        "They won’t rehouse me after domestic abuse",
        "My child has special needs but they ignore that",
        "They closed my case for missing an appointment",
        "They said I’m intentionally homeless after fleeing abuse",
        "My case was transferred and no one knows my history",
        "I can’t access support because I’m over 25",
        "They gave me a damp room in a shared house",
        "I need urgent help before I’m on the street",
        "They offered private rent but I can’t afford the deposit",
        "I’ve been sofa-surfing and can’t get priority",
        "My kids are in temporary school because of moves",
        "They said no duty owed because of my income",
        "They reopened my case after 12 months",
        "They blame me for not finding my own place",
        "I need an interpreter at my review interview",
        "They lost my medical evidence so closed my file",
        "They said the only offer is near my children's school",
        "I’ve been sofa-surfing and have no permanent place to stay",
        "They placed me in a hostel with no privacy",
        "My temporary accommodation is overcrowded and unsafe",
        "They said I’m not priority even though I’m pregnant",
        "I’ve been refused because I don’t have a local connection",
        "They offered me housing 60 miles away from my children’s school",
        "My homelessness application was closed after one missed call",
        "They told me to apply for private rent when I can’t afford it",
        "I was discharged from care with no suitable housing plan",
        "They said I’m intentionally homeless after fleeing abuse",
        "I need emergency accommodation but they put me on a waiting list",
        "They placed me in a B&B with no cooking facilities",
        "My temporary flat is infested with bedbugs",
        "They lost my paperwork and restarted my application",
        "I’ve been on the priority list for over six months with no offer",
        "They say they can’t help because I have a partner",
        "I’ve been moved between hostels with no notice",
        "They offered me a tent on a campsite instead of a flat",
        "My children were moved away from their school catchment",
        "They refuse to consider my mental health needs in rehousing",
        "They closed my case when funding ran out",
        "I need support to find private accommodation but they won’t help",
        "They placed me in housing with no heating in winter",
        "I was told to go back to my previous abusive landlord",
        "They keep rescheduling my housing review meetings",
        "My temporary hostel has no heating in sub-zero temperatures",
        "They placed me in accommodation with no running water",
        "I've been moved three times in a month and have nowhere to unpack."

    ],

    "label": [

        
        *["Disrepair and Conditions"] * 50,
        *["Tenancy, Transfer, Rent and Eviction"] * 50,
        *["Accessibility and Discrimination"] * 50,
        *["Complaints and Ombudsman"] * 50, 
        *["Antisocial Behaviour/Neighbour Conflict"] * 50,
        *["Homelessness"] * 50
    ]
}

df = pd.DataFrame(training_queries)

pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range = (1,2))),
    ('clf', LogisticRegression(solver = 'liblinear', multi_class = 'ovr'))
    ])
    
pipeline.fit(df["query"], df["label"])

def category_classifier():
    query = input('Welcome to StandUp! Please type your housing-related query:\n').strip()
    label = pipeline.predict([query])[0]
    print(f'Your concern relates to: {label}. Is this correct? Please type yes or no')
    ans = input('> ').strip().lower()
    confirmed = True if ans in ('yes', 'y') else False if ans in ('no', 'n') else None
    return label, confirmed

        

category_classifier()



